// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcl3U3KcMWyTHi3NnGA3wF0gzWS1nM47I',
    appId: '1:712681728900:web:3f4e6228dda211ff470bd1',
    messagingSenderId: '712681728900',
    projectId: 'zr3ahtck',
    authDomain: 'zr3ahtck.firebaseapp.com',
    storageBucket: 'zr3ahtck.firebasestorage.app',
    measurementId: 'G-H0MY5VEV18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgjU6n3DaOMojTD0_lbNh2Nkq2Y4EyRaw',
    appId: '1:712681728900:android:8cb1d48cd6d0bd61470bd1',
    messagingSenderId: '712681728900',
    projectId: 'zr3ahtck',
    storageBucket: 'zr3ahtck.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ9h2WrXXM9ZHsKSkJHHubZvsUkGCZ9oA',
    appId: '1:712681728900:ios:4f633d4eea4ea2a2470bd1',
    messagingSenderId: '712681728900',
    projectId: 'zr3ahtck',
    storageBucket: 'zr3ahtck.firebasestorage.app',
    iosBundleId: 'com.example.zr3ahtechflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ9h2WrXXM9ZHsKSkJHHubZvsUkGCZ9oA',
    appId: '1:712681728900:ios:4f633d4eea4ea2a2470bd1',
    messagingSenderId: '712681728900',
    projectId: 'zr3ahtck',
    storageBucket: 'zr3ahtck.firebasestorage.app',
    iosBundleId: 'com.example.zr3ahtechflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcl3U3KcMWyTHi3NnGA3wF0gzWS1nM47I',
    appId: '1:712681728900:web:17ae747c61e0bfa7470bd1',
    messagingSenderId: '712681728900',
    projectId: 'zr3ahtck',
    authDomain: 'zr3ahtck.firebaseapp.com',
    storageBucket: 'zr3ahtck.firebasestorage.app',
    measurementId: 'G-YM9WLKHVRC',
  );
}
